# Generated by Django 5.0.2 on 2024-03-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='propietario',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
