# Generated by Django 5.0.2 on 2024-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_alojamiento_propietario_alojamiento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='ciudad',
            field=models.CharField(default='No determinado', max_length=200),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='direccion',
            field=models.CharField(default='No determinado', max_length=200),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
