# Generated by Django 5.0.2 on 2024-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alojamiento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alojamiento/'),
        ),
    ]
